modLoader = "kotlinforforge"
loaderVersion = "[4,)"
license = "AGPL-3.0"
issueTrackerURL = "https://github.com/Earu/afkmon-mc/issues"

[[mods]]
modId = "afk"
version = "${version}"
displayName = "afkmon-mc"
logoFile = "assets/afk/icon.png"
description = '''AFK detection with rotating status rings around away players.'''
authors = "Earu"

[[dependencies.afk]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.afk]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
