modLoader = "kotlinforforge"
loaderVersion = "[5,)"
license = "AGPL-3.0"
issueTrackerURL = "https://github.com/Earu/afkmon-mc/issues"

[[mods]]
modId = "afk"
version = "${version}"
displayName = "afkmon-mc"
logoFile = "assets/afk/icon.png"
description = '''AFK detection with rotating status rings around away players.'''
authors = "Earu"

[[mixins]]
config = "afk.mixins.json"

[[dependencies.afk]]
modId = "neoforge"
type = "required"
versionRange = "[21.11.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.afk]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11]"
ordering = "NONE"
side = "BOTH"
